/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminWeeksRouteImport } from './routes/admin/weeks'
import { Route as ApiPublicPaydunyaIpnRouteImport } from './routes/api/public/paydunya-ipn'
import { Route as ApiPublicPushKeyRouteImport } from './routes/api/public/push-key'
import { Route as ApiPublicPushWebhookRouteImport } from './routes/api/public/push-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWeeksRoute = AdminWeeksRouteImport.update({
  id: '/weeks',
  path: '/weeks',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaydunyaIpnRoute = ApiPublicPaydunyaIpnRouteImport.update({
  id: '/api/public/paydunya-ipn',
  path: '/api/public/paydunya-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushKeyRoute = ApiPublicPushKeyRouteImport.update({
  id: '/api/public/push-key',
  path: '/api/public/push-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushWebhookRoute = ApiPublicPushWebhookRouteImport.update({
  id: '/api/public/push-webhook',
  path: '/api/public/push-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/weeks': typeof AdminWeeksRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/push-key': typeof ApiPublicPushKeyRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/weeks': typeof AdminWeeksRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/push-key': typeof ApiPublicPushKeyRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/weeks': typeof AdminWeeksRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/push-key': typeof ApiPublicPushKeyRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/commande'
    | '/confirmation'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/weeks'
    | '/admin/'
    | '/api/public/paydunya-ipn'
    | '/api/public/push-key'
    | '/api/public/push-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/commande'
    | '/confirmation'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/weeks'
    | '/admin'
    | '/api/public/paydunya-ipn'
    | '/api/public/push-key'
    | '/api/public/push-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/commande'
    | '/confirmation'
    | '/reset-password'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/weeks'
    | '/admin/'
    | '/api/public/paydunya-ipn'
    | '/api/public/push-key'
    | '/api/public/push-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommandeRoute: typeof CommandeRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPaydunyaIpnRoute: typeof ApiPublicPaydunyaIpnRoute
  ApiPublicPushKeyRoute: typeof ApiPublicPushKeyRoute
  ApiPublicPushWebhookRoute: typeof ApiPublicPushWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/weeks': {
      id: '/admin/weeks'
      path: '/weeks'
      fullPath: '/admin/weeks'
      preLoaderRoute: typeof AdminWeeksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paydunya-ipn': {
      id: '/api/public/paydunya-ipn'
      path: '/api/public/paydunya-ipn'
      fullPath: '/api/public/paydunya-ipn'
      preLoaderRoute: typeof ApiPublicPaydunyaIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-key': {
      id: '/api/public/push-key'
      path: '/api/public/push-key'
      fullPath: '/api/public/push-key'
      preLoaderRoute: typeof ApiPublicPushKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-webhook': {
      id: '/api/public/push-webhook'
      path: '/api/public/push-webhook'
      fullPath: '/api/public/push-webhook'
      preLoaderRoute: typeof ApiPublicPushWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWeeksRoute: typeof AdminWeeksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWeeksRoute: AdminWeeksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommandeRoute: CommandeRoute,
  ConfirmationRoute: ConfirmationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPaydunyaIpnRoute: ApiPublicPaydunyaIpnRoute,
  ApiPublicPushKeyRoute: ApiPublicPushKeyRoute,
  ApiPublicPushWebhookRoute: ApiPublicPushWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
